### PR TITLE
Restructure Django apps

### PR DESCRIPTION
**Pull request by jerbob**
This PR contains a bunch of sweeping changes to the project's app names and scopes. The goal here is to get rid of any redundant apps, and merge any apps whose scopes intersect.

### CODE REVIEW

**Review by jchristgit — APPROVED** [review]

**Review by jchristgit — APPROVED** [review]

**Review by jchristgit — APPROVED** [review]

**Comment by jchristgit** [comment]
@david-cooke is working on fixing the merge conflicts here.

**Comment by jchristgit** [comment]
Hello @jerbob, just checking in to see how you're doing. Do you need help with this PR?

**Comment by jchristgit** [comment]
@jerbob do we _need_ the migrations to move data over? We only ever run the app for a single event anyways.

**Review by jchristgit — CHANGES_REQUESTED** [review]
Jeremiah,

While I highly appreciate the amount of effort that has flown into this pull
request, in its current state, it is not possible to actually _review_ the code,
as I am plagued with local setup errors. I understand it's hard to keep a pull
request of this size in sync with the master branch, but I cannot adjust half
the project when testing it locally. I've encountered a number of issues whilst
trying to set this up:

- `poetry.lock` was not working properly, and caused `poetry` to crash with an
  error. Running `poetry lock` fixed it.

- After building the project in `docker-compose` and starting it, it crashed
  multiple times. For the following reasons, in no particular order:

	- Unexpected indents
  - Undefined imports
  - Missing migrations

- I tried to fix the missing imports by using `flake8`, or at least find them,
  but `flake8` also crashes out with an error, I assume due to a configuration
error:

```py
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pylint" due
to cannot import name 'MergedConfigParser' from 'flake8.options.config' (...).
```

I believe the majority of these problems is caused by the recent merge with
option `-X ours`. I understand it's annoying to fix a big merge conflict, but
perhaps we should roll the merge back, and try to resolve it one-by-one?

**Comment by jerbob** [comment]
Johannes,

While I highly appreciate your need to check in on open PRs as the RACTF Principal Software Engineer, this PR is marked as a "Draft". PRs that are marked as a "Draft" are generally not yet ready for review, which is why I've explicitly marked this PR as a "Draft" (it is not yet ready for review). When it is ready for a review, I will mark it as "Ready to review" which implies that the PR in question is ready to be reviewed (it is not). You're right that a lot of work's been put into this PR, but it's still far from done, which is why I haven't moved it from "Draft" to "Ready to review" just yet. I will remove this PR from "Draft" and into "Ready to review" once the PR is viable for a code review.

Your unsolicited review is highly appreciated, but the points raised are all in reference to aspects of this PR that will change long before I move the PR from "Draft" (not ready for a review) to "Ready to review" (ready for a code review). In particular, issues raised by a faulty merge commit that can be rectified by reverting and rebasing manually.

You can find out more about "Draft" pull requests in this blog post: https://github.blog/2019-02-14-introducing-draft-pull-requests

**Comment by jerbob** [comment]
As an addendum, I will click this button below my comment when the pull request is ready for a review (it is not):
image

Thank you for your service.

**Comment by jchristgit** [comment]
I'm sorry, Jeremiah. I will take my review down immediately, and implement measures to prevent this from happening in the future. I will not leave unsolicited reviews on any Really Awesome CTF Ltd. repositories in the future, and I will ensure that any review I leave is friendly and welcoming as opposed to being this hostile. I apologize for my actions.

**Comment by jerbob** [comment]
Johannes,

thanks

**Comment by 0x4da** [comment]
:cry:

**Comment by jchristgit** [comment]
As a longtime fan of the RACTF backend, I'm sad to see this go.

When I was a child, I loved learning about new developments of the RACTF
backend app restructure pull request. Whenever I returned from school, it was
the first question I wanted answered. The lack of updates was always both
interesting and sad to me, and I was always hoping for a timely update on such
an important topic.

As I grew older, my childlike fascination with the lack of updates on the pull
request grew into a more stoic lifeform, and the overall stagnation of the pull
request slowly started to affect my own life. Looking for a way to get out, I
learnt Python programming. I am sad that to this day, I have not been able to
provide any net benefit to this pull request, despite my ability to read basic
Python code and even perhaps write a bit with the help of modern assistant
tooling.

Jeremiah, thank you for all your hard work. I can understand why you've chosen
this step, and let it be known that your cries for aid in the deep trenches of
refactoring this code have not been left unheard. I can assure you that life
always finds a way.

**Pull request closed without merging**
