### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tiwari27**

### CODE REVIEW

**Comment by tiwari27** [comment]
Is this is right??

**Review by shubham9702 — CHANGES_REQUESTED** [review]
That's right this introduction is enough well done keep doing.
This introduction is nicely written that anyone can understand this.

**Review by shubham9702 — CHANGES_REQUESTED** [review]
That's right this introduction is enough, nicley explained well done.

**Comment by ashish756** [comment]
That right

**Pull request closed without merging**
