### PR TITLE
Fix negative points from decay plugin

### LINKED ISSUE #258: Decay scoring leads to teams/users with incorrect or negative points after incorrect solves
**Describe the bug**
If an event is using decay scoring, teams and users with incorrect solves are not correctly filtered out when updating points values. If Team A submits an incorrect flag for challenge 1 and then Team B solves it, the decay scoring will remove around 4 points from Team A because of the decrease in the challenge's points value.

**To Reproduce**
1. Create multiple teams
2. Create a challenge with decay scoring enabled
3. Submit an incorrect flag on one team
4. Solve the challenge on other teams

**Expected behavior**
Teams and users with incorrect solves should not be included in points adjustments when a challenge's points value changes

**Additional context**
[The code that is incorrectly filtering solves](https://github.com/ractf/core/blob/master/src/plugins/points/decay.py#L25-L26)

### PR DESCRIPTION
**Pull request by 0x4da**
Fixes #258

### CODE REVIEW

**Review by jchristgit — APPROVED** [review]

**Comment by jchristgit** [comment]
There's a conflict in here, could you resolve it?

**Review by thebeanogamer — APPROVED** [review]
I think we accidentally merged this at some point, this PR only adds a test

**Comment by 0x4da** [comment]
oh yeah we did, was merged in a random other pr because i cant git

**Comment by thebeanogamer** [comment]
This test needs to actually pass. This is broken in production if it's broken here.

**Pull request merged**
