### PR TITLE
Python 3.9 Support

### PR DESCRIPTION
**Pull request by david-cooke**
tests pass, idk if it runs

### CODE REVIEW

**Review by jerbob — APPROVED** [review]

**Review by AmusedNetwork — APPROVED** [review]

**Comment by thebeanogamer** [comment]
"Tests pass"

image

**Comment by david-cooke** [comment]
> "Tests pass"
> 
> image

works on my machine

**Comment by thebeanogamer** [comment]
We used Poetry Preview before async downloads were on mainline. I've removed that to make test pass, as async downloads are now in the release version.

**Comment by david-cooke** [comment]
do we actually have to unit test the fucking 404 view

**Comment by david-cooke** [comment]
tbf it wasnt actually working so we probably should

**Comment by thebeanogamer** [comment]
This seems to work. Get a test for that 404 and I'll approve it.

**Review by thebeanogamer — APPROVED** [review]

**Pull request merged**
